stages:
  - build
  - create_image
  - deploy

variables:
  NODE_IMAGE: node:18-alpine
  SECURE_FILES_DOWNLOAD_PATH: "./"

build:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd SkyShop
    - echo "Instalando dependencias"
    - npm i
    - echo "Ejecutando build"
    - npm run build
  only:
    - main

create_image:
  stage: create_image
  image: docker:stable
  services:
    - docker:dind
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd SkyShop
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t juancruzmarzetti/sky-shop:front .
    - docker push juancruzmarzetti/sky-shop:front
    - rm juankeys.pem
  only:
    - main

deploy:
  stage: deploy
  image: python:3.9
  before_script:
    - cd SkyShop
    - echo "$JUANKEYS" > juankeys.pem
    - chmod 600 juankeys.pem
    - pip install ansible
    - mkdir ~/.ssh
    - touch ~/.ssh/config
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - ansible-playbook -i hosts.ini playbook.yaml --key-file "juankeys.pem"
    - rm juankeys.pem
  only:
    - main
